### ISSUE TITLE
Dont working for me

### ISSUE THREAD

**Issue by Sfield111** [SkyEmie/batch-obfuscator#2]
If i use your site and obfsucate my bat it wont working

**Comment by SkyEmie** [comment]
(Thank you for not advertising again your website Redcarred2)
Otherwise everything works perfectly @Sfield111 , if you have a problem, do not hesitate to provide a screenshot 😉

**Comment by Sfield111** [comment]
Now it's work fine, idk why earlier it don't work . Thanks <3
